const fs = require('fs');
let content = fs.readFileSync('src/components/ParadeStateFormattedView.tsx', 'utf8');

const target1 = "  };\n\n  return (\n    <div className=\\"space-y-6\\">";
const replace1 = "  };\n\n  const contentBody = (\n    <div className=\\"space-y-6\\">";
content = content.replace(target1, replace1);

const target2 = "      />\n    </div>\n  );\n}";
const replace2 = "      />\n    </div>\n  );\n\n  if (isPrintMode) {\n    return (\n      <div className=\\"fixed inset-0 z-[100] flex flex-col bg-slate-900/90 backdrop-blur-sm overflow-hidden print:bg-white print:block\\">\n        <div className=\\"flex-none bg-slate-900 border-b border-slate-700 p-4 flex items-center justify-between shadow-2xl print:hidden z-10 sticky top-0\\">\n          <div className=\\"text-white font-bold text-lg hidden sm:block\\">Print Preview - ${isMultiDay ? 'Multi-Day ' : ''}${isPtDocument ? 'PT' : 'Parade'} State</div>\n          <div className=\\"flex items-center space-x-3 text-white\\">\n            <button\n              onClick={() => {\n                document.title = `${isPtDocument ? 'PT' : 'Parade'}_State_${isMultiDay ? 'MultiDay' : fromDate}`;\n                window.print();\n              }}\n              className=\\"flex items-center space-x-2 px-6 py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl font-black text-sm shadow-lg shadow-emerald-900/20 transition-all cursor-pointer\\"\n            >\n              <Printer className=\\"w-5 h-5\\" />\n              <span>Official Export / Print</span>\n            </button>\n            <button\n              onClick={onClosePrintMode}\n              className=\\"flex items-center space-x-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white rounded-xl font-bold text-sm transition-colors cursor-pointer ml-3\\"\n            >\n              <X className=\\"w-5 h-5\\" />\n              <span>Close</span>\n            </button>\n          </div>\n        </div>\n        <div className=\\"flex-1 overflow-y-auto p-4 sm:p-8 flex justify-center print:p-0 print:overflow-visible print:block\\">\n          <div className=\\"w-full max-w-none 2xl:w-[98%] print:w-auto mx-auto print:mx-0 print:border-none print:rounded-none print:shadow-none bg-transparent text-black dark:text-white\\">\n            {contentBody}\n          </div>\n        </div>\n      </div>\n    );\n  }\n\n  return contentBody;\n}";

content = content.replace(target2, replace2);
fs.writeFileSync('src/components/ParadeStateFormattedView.tsx', content);
