const fs = require('fs');
let code = fs.readFileSync('src/components/DutyRatioMatrixView.tsx', 'utf-8');

code = code.replace(
  '        </button>\n      </div>\n    </div>\n      </div>\n    </div>\n\n    {/* TAB NAVIGATION */}\n    <div className="flex flex-wrap space-x-1 sm:space-x-2 bg-slate-200/50 dark:bg-slate-800/50 p-1.5 rounded-xl w-full max-w-3xl mt-4">\n      <button \n        onClick={() => setViewMode(\'TOTAL_DUTY\')}\n        className={`flex-1 py-2 px-2 sm:px-4 text-xs sm:text-sm font-bold rounded-lg transition-colors ${viewMode === \'TOTAL_DUTY\' ? \'bg-white dark:bg-slate-700 text-indigo-700 dark:text-indigo-300 shadow-sm\' : \'text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700/50\'}`}\n      >Total Duty</button>\n      <button \n        onClick={() => setViewMode(\'MANPOWER\')}\n        className={`flex-1 py-2 px-2 sm:px-4 text-xs sm:text-sm font-bold rounded-lg transition-colors ${viewMode === \'MANPOWER\' ? \'bg-white dark:bg-slate-700 text-indigo-700 dark:text-indigo-300 shadow-sm\' : \'text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700/50\'}`}\n      >Manpower</button>\n      <button \n        onClick={() => setViewMode(\'DUTY_DISTRIBUTION\')}\n        className={`flex-1 py-2 px-2 sm:px-4 text-xs sm:text-sm font-bold rounded-lg transition-colors ${viewMode === \'DUTY_DISTRIBUTION\' ? \'bg-white dark:bg-slate-700 text-indigo-700 dark:text-indigo-300 shadow-sm\' : \'text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700/50\'}`}\n      >Distribution</button>\n      <button \n        onClick={() => setViewMode(\'DUTY_RATIO\')}\n        className={`flex-1 py-2 px-2 sm:px-4 text-xs sm:text-sm font-bold rounded-lg transition-colors ${viewMode === \'DUTY_RATIO\' ? \'bg-white dark:bg-slate-700 text-indigo-700 dark:text-indigo-300 shadow-sm\' : \'text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700/50\'}`}\n      >Duty Ratio</button>\n    </div>\n    </div>',
  '        </button>\n      </div>\n    </div>\n\n    {/* TAB NAVIGATION */}\n    <div className="flex flex-wrap space-x-1 sm:space-x-2 bg-slate-200/50 dark:bg-slate-800/50 p-1.5 rounded-xl w-full max-w-3xl mt-4">\n      <button \n        onClick={() => setViewMode(\'TOTAL_DUTY\')}\n        className={`flex-1 py-2 px-2 sm:px-4 text-xs sm:text-sm font-bold rounded-lg transition-colors ${viewMode === \'TOTAL_DUTY\' ? \'bg-white dark:bg-slate-700 text-indigo-700 dark:text-indigo-300 shadow-sm\' : \'text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700/50\'}`}\n      >Total Duty</button>\n      <button \n        onClick={() => setViewMode(\'MANPOWER\')}\n        className={`flex-1 py-2 px-2 sm:px-4 text-xs sm:text-sm font-bold rounded-lg transition-colors ${viewMode === \'MANPOWER\' ? \'bg-white dark:bg-slate-700 text-indigo-700 dark:text-indigo-300 shadow-sm\' : \'text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700/50\'}`}\n      >Manpower</button>\n      <button \n        onClick={() => setViewMode(\'DUTY_DISTRIBUTION\')}\n        className={`flex-1 py-2 px-2 sm:px-4 text-xs sm:text-sm font-bold rounded-lg transition-colors ${viewMode === \'DUTY_DISTRIBUTION\' ? \'bg-white dark:bg-slate-700 text-indigo-700 dark:text-indigo-300 shadow-sm\' : \'text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700/50\'}`}\n      >Distribution</button>\n      <button \n        onClick={() => setViewMode(\'DUTY_RATIO\')}\n        className={`flex-1 py-2 px-2 sm:px-4 text-xs sm:text-sm font-bold rounded-lg transition-colors ${viewMode === \'DUTY_RATIO\' ? \'bg-white dark:bg-slate-700 text-indigo-700 dark:text-indigo-300 shadow-sm\' : \'text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700/50\'}`}\n      >Duty Ratio</button>\n    </div>\n    </div>'
);

fs.writeFileSync('src/components/DutyRatioMatrixView.tsx', code);
